spin_version = "1"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = "good first issue"
name = "goodfirstissue"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "api"
source = "main.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"

