spin_manifest_version = "1"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""
name = "goodfirstissue"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "backend"
source = "main.wasm"
allowed_http_hosts = ["api.twitter.com", "bsky.social", "opengraph.githubassets.com", "github.com"]
key_value_stores = ["default"]
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod", "spin.toml"]
