provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  goodfirstissue:
    lang: golang-middleware
    handler: ./goodfirstissue
    image: goodfirstissue:0.1
    labels:
      com.openfaas.scale.zero: false
    secrets:
      - goodfirstissue
