name: Deploy Good First Issue Bot
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup spin
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ github.token }}

      - name: "Install Go"
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          
      - name: "Install TinyGo"
        uses: rajatjindal/setup-actions/tinygo@v0.0.1
        with:
          version: "v0.27.0"

      - name: build and deploy
        uses: fermyon/actions/spin/deploy@v1
        id: deploy
        with:
          fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}
          manifest_file: spin.toml
          key_values: |-
            twitter:consumerKey=${{ secrets.TWITTER_CONSUMER_KEY }}
            twitter:consumerToken=${{ secrets.TWITTER_CONSUMER_TOKEN }}
            twitter:token=${{ secrets.TWITTER_TOKEN }}
            twitter:tokenSecret=${{ secrets.TWITTER_TOKEN_SECRET }}
